### ISSUE TITLE
Problem with storybook and HOC

### ISSUE THREAD

**Issue by miketheanimal** [kadirahq/babel-plugin-react-docgen#19]
Running storybook throws an error in babel-plugin-react-docgen in the code below

    export default function Modal (component) {
        return class extends component {
            constructor (...args) {
                super(...args) ;
                ....
                }

            ......
            }
        }

    ERROR in ./src/lib/modal.js
    Module build failed: TypeError: /tmp/react/src/lib/modal.js: Cannot read property 'name' of null
        at PluginPass.Class (/tmp/react/node_modules/@kadira/storybook/node_modules/babel-plugin-react-docgen/lib/index.js:18:37)
        at newFn (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
        at NodePath._call (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
        at TraversalContext.visitQueue (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit (/tmp/react/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
     @ ./src/containers/campaign/savecampaign/savecampaign.js 17:13-42

If i change the return to just the function argument the storybook runs OK.

If I edit /tmp/react/node_modules/@kadira/storybook/node_modules/babel-plugin-react-docgen/lib/index.js and insert a check about line 17 then again storybook runs.

        ....
        }
        if (!path.parentPath.node.id) {
          return;
        }
        var className = path.parentPath.node.id.name;
        ....

I'm guessing docgen is missing a particular case?

Hope this makes sense (and is readable ....)

**Comment by madushan1000** [comment]
Which storybook version are you running?

**Comment by madushan1000** [comment]
Doesn't matter, I can replicate the issue in the latest version. I'll take a look.

**Comment by arunoda** [comment]
We fixed this and release a new version of storybook.

**Comment by miketheanimal** [comment]
Thanks!
